### ISSUE TITLE
Binaries execution issues

### ISSUE THREAD

**Issue by pablo-lamtenzan** [pablo-lamtenzan/miniShell#13]
ISSUES:

1) Minishell must find executables when they are located in the same directory and var PATH is empty.
>$ export PATH="" ; touch exec; ./exec

2) Minishell must disable the builtin ls if the path is unset. This issue could just be unset builtin.
>$ unset $PATH ; ls

3) Same than 2
>$ export PATH="/" ; ls

4) Issues executing a forbidden executable. Must print properly and return a non-zero integer+
>$ touch file ; chmod 0 file ; ./file

**Comment by ClemaX** [comment]
There is no builtin ls, so probably unset doesn't work.

**Comment by pablo-lamtenzan** [comment]
I've just realize we don't have builtins export and unset LMAO. All the code is commented. I think is better if you develop them (cause we need to use your and because you already did it one time) but i can try to do them to if you have no time :)

**Comment by pablo-lamtenzan** [comment]
we need to use your lib*

**Comment by pablo-lamtenzan** [comment]
Ok i ve tried to implement export and i did a experimental version. Need to be checked and tested.
