### ISSUE TITLE
Builtin Exit pipes interactions

### ISSUE THREAD

**Issue by pablo-lamtenzan** [pablo-lamtenzan/miniShell#18]
Builtin exit should not terminate Minishell in a piped command
>$ exit | ls

**Comment by ClemaX** [comment]
Yes, maybe we should handle subshell?

**Comment by pablo-lamtenzan** [comment]
I think this could be the answer but I can solve this issue with a simple flag. I think if we implement subshell we should handle all the cases and I don't know if is worth (cause this is not in the subject)
