### ISSUE TITLE
Local variable issues

### ISSUE THREAD

**Issue by pablo-lamtenzan** [pablo-lamtenzan/miniShell#22]
- Just declare a var and check the env ? Don't undersand
- export var=old ; export var=new ; env error: stdout does not match
- export var=value ; export var= ; env error: stdout does not match
- unset "var" ; write in out $var $another: error: var is displayed in out
- var= ; write in out $var: error stdout

*** This is copy-paste from 42sh_tester_issues.txt (line 171) ***

**Comment by ClemaX** [comment]
Export builtin does not work:
```
[chamada]$ var=old
[chamada]$ export var=new
[chamada]$ echo $var
old
[chamada]$
```
