### ISSUE TITLE
Tilde expansion

### ISSUE THREAD

**Issue by pablo-lamtenzan** [pablo-lamtenzan/miniShell#23]
As a bonus not in the subject this is optional

see 42sh_tester_issues.txt (line 82) or execute
>$ bash ~/42ShellTester/42ShellTester.sh ./minishell --show-success --reference "bash" --filter "tilde-expansion" --hard

**Comment by ClemaX** [comment]
This works:
```
[chamada]$ echo ~
/Users/chamada
[chamada]$ echo ~+
/Users/chamada/Projects/minishell
[chamada]$ echo ~-
/Users/chamada
```
But i'm going to check with the tester

**Comment by pablo-lamtenzan** [comment]
Finally ?

**Comment by pablo-lamtenzan** [comment]
i' ve checked a lot of tests and the 42sh tester is useful but sometimes has some incoherences. I think the tilde is correct if minish tests results are as bash
