### ISSUE TITLE
Litle termcaps exeption

### ISSUE THREAD

**Issue by pablo-lamtenzan** [pablo-lamtenzan/miniShell#30]
This is a crazy error:

Write a line shorter than the terminal width, then compress the terminal until split the line in 2 lines, when make the term larger and put the split-ed 2 lines in one line another time, after that, move the cursor et the middle of this line and write until jump the to next line: there's the bug: the right part of the line is deleted while writing and/but written again while deleting.

**Comment by ClemaX** [comment]
This is because I do not redraw existing lines after writing. I forgot to fix this yesterday.
